// SPDX-FileCopyrightText: 2026 Wizards Den contributors
// SPDX-FileCopyrightText: 2026 Sector Vestige contributors (modifications)
// SPDX-FileCopyrightText: 2021 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 mirrorcult <lunarautomaton6@gmail.com>
// SPDX-FileCopyrightText: 2024 SlamBamActionman <83650252+SlamBamActionman@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Brandon Li <48413902+aspiringLich@users.noreply.github.com>
// SPDX-FileCopyrightText: 2026 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
// SPDX-FileCopyrightText: 2026 ReboundQ3 <22770594+ReboundQ3@users.noreply.github.com>
// SPDX-FileCopyrightText: 2026 Голубь <124601871+Golubgik@users.noreply.github.com>
//
// SPDX-License-Identifier: MIT

using System;
using System.Linq; // SV - option icons
using Content.Client.Stylesheets;
using Content.Shared.Ghost;
using Content.Shared.Ghost.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement; // SV - option icons
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Voting.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class VotePopup : Control
    {
        [Dependency] private IGameTiming _gameTiming = default!;
        [Dependency] private IVoteManager _voteManager = default!;
        [Dependency] private IEntityNetworkManager _net = default!;
        [Dependency] private IResourceCache _resourceCache = default!; // SV - option icons
        [Dependency] private ILogManager _logManager = default!; // SV - option icons

        private const float IconHeight = 96; // SV - Height of the option icons in virtual pixels. Their width follows the column they sit in.
        private readonly VoteManager.ActiveVote _vote;
        private readonly Button[] _voteButtons;
        private readonly Label?[] _voteCountLabels; // SV - option icons: vote count under the name on icon buttons
        private readonly NetEntity? _targetEntity;

        public VotePopup(VoteManager.ActiveVote vote)
        {
            _vote = vote;
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);

            Stylesheet = IoCManager.Resolve<IStylesheetManager>().SheetSystem;

            if (_vote.TargetEntity != null && _vote.TargetEntity != 0)
            {
                _targetEntity = new NetEntity(_vote.TargetEntity.Value);
                FollowVoteTarget.Visible = true;
                FollowVoteTarget.OnPressed += _ => AttemptFollowVoteEntity();
            }

            Modulate = Color.White.WithAlpha(0.75f);
            _voteButtons = new Button[vote.Entries.Length];
            _voteCountLabels = new Label?[vote.Entries.Length]; // SV - option icons
            var group = new ButtonGroup();

            for (var i = 0; i < _voteButtons.Length; i++)
            {
                var button = new Button
                {
                    ToggleMode = true,
                    Group = group
                };
                _voteCountLabels[i] = AddIcon(button, vote.Entries[i].Icon); // SV - option icons
                _voteButtons[i] = button;
                VoteOptionsContainer.AddChild(button);
                var i1 = i;
                button.OnPressed += _ => _voteManager.SendCastVote(vote.Id, i1);
            }

            // SV - With icons the popup takes all the width it can get (up to MaxWidth) and the icons stretch to fit,
            // so the buttons never grow past the background panel.
            if (vote.Entries.Any(entry => entry.Icon != null))
                MinWidth = MaxWidth;
        }

        public void UpdateData()
        {
            VoteTitle.SetMessage(FormattedMessage.FromMarkupPermissive(_vote.Title)); // SV - Add markup
            VoteCaller.Text = Loc.GetString("ui-vote-created", ("initiator", _vote.Initiator));

            for (var i = 0; i < _voteButtons.Length; i++)
            {
                var entry = _vote.Entries[i];
                if (_voteCountLabels[i] is { } voteCount) // SV - option icons: name and count on separate lines
                {
                    _voteButtons[i].Text = entry.Text;
                    voteCount.Visible = _vote.DisplayVotes;
                    voteCount.Text = Loc.GetString("ui-vote-icon-button-votes", ("votes", entry.Votes));
                }
                else if (_vote.DisplayVotes)
                {
                    _voteButtons[i].Text = Loc.GetString("ui-vote-button", ("text", entry.Text), ("votes", entry.Votes));
                }
                else
                {
                    _voteButtons[i].Text = Loc.GetString("ui-vote-button-no-votes", ("text", entry.Text));
                }

                if (_vote.OurVote == i)
                    _voteButtons[i].Pressed = true;
            }
        }

        /// <summary>
        /// SV - Puts an icon above the button's label and a vote count label below it.
        /// Returns the vote count label, or null when the button gets no icon and is left untouched.
        /// </summary>
        private Label? AddIcon(Button button, string? iconPath)
        {
            if (iconPath == null)
                return null;

            if (!_resourceCache.TryGetResource<TextureResource>(new ResPath(iconPath), out var texture))
            {
                _logManager.GetSawmill("vote").Warning($"Vote option icon not found: {iconPath}");
                return null;
            }

            // The icon asks for no width of its own, so the grid divides the popup width evenly between the columns
            // and the icon scales down to whatever its column gets. It never draws larger than the texture.
            var icon = new TextureRect
            {
                Texture = texture,
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                CanShrink = true,
                SetHeight = IconHeight,
                HorizontalExpand = true,
            };

            button.HorizontalExpand = true;
            button.ClipText = true;
            button.TextAlign = Label.AlignMode.Center;

            // Move the label the Button already made below the icon so Text and styling keep working.
            var label = button.Label;
            label.Orphan();

            // The vote count gets its own line so the map name keeps the full column width.
            var voteCount = new Label
            {
                StyleClasses = { StyleClass.LabelSubText },
                Align = Label.AlignMode.Center,
                ClipText = true,
            };

            var box = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
            };

            box.AddChild(icon);
            box.AddChild(label);
            box.AddChild(voteCount);
            button.AddChild(box);
            return voteCount;
        }

        private void AttemptFollowVoteEntity()
        {
            if (_targetEntity != null)
            {
                var msg = new GhostWarpToTargetRequestEvent(_targetEntity.Value);
                _net.SendSystemNetworkMessage(msg);
            }
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            // Logger.Debug($"{_gameTiming.ServerTime}, {_vote.StartTime}, {_vote.EndTime}");

            var curTime = _gameTiming.RealTime;
            var timeLeft = _vote.EndTime - curTime;
            if (timeLeft < TimeSpan.Zero)
                timeLeft = TimeSpan.Zero;

            // Round up a second.
            timeLeft = TimeSpan.FromSeconds(Math.Ceiling(timeLeft.TotalSeconds));

            TimeLeftBar.Value = Math.Min(1, (float) ((curTime.TotalSeconds - _vote.StartTime.TotalSeconds) /
                                                     (_vote.EndTime.TotalSeconds - _vote.StartTime.TotalSeconds)));

            TimeLeftText.Text = $"{timeLeft:m\\:ss}";
        }
    }
}
