- type: startingGear
  id: SV_AyanianMarineGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitAyanianMarine
    back: ClothingBackpackSatchel
    outerClothing: ClothingOuterAyanianMarine
    id: VisitorPDA
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesBootsJack
    belt: ClothingBeltSecurity
    head: ClothingHeadHatBeretFederation

- type: startingGear
  id: SV_AyanianAdmiralGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitAyanianMarine
    back: ClothingBackpackSatchel
    outerClothing: ClothingOuterCoatAyanianAdmiral
    id: VisitorPDA
    gloves: ClothingHandsGlovesHop
    shoes: ClothingShoesBootsLaceup
    head: ClothingHeadHatAdmiralFederation

- type: startingGear
  id: SV_AndalusianHighNoble
  equipment:
    jumpsuit: ClothingUniformJumpsuitAndalusian
    back: ClothingBackpackSatchel
    neck: ClothingNeckCloakAndalusian
    id: VisitorPDA
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesBootsLaceup
    head: ClothingHeadHatTricornAndalusian
