# SPDX-FileCopyrightText: 2025 Sector-Vestige contributors
# SPDX-FileCopyrightText: 2025 Sector Vestige contributors (modifications)
# SPDX-FileCopyrightText: 2025 JuneSzalkowska <juneowo69@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: startingGear
  id: SV_AltGorlexRep
  equipment:
    jumpsuit: ClothingUniformJumpsuitAyanianMarine
    back: ClothingBackpackSatchelSalvage
    outerClothing: ClothingOuterWinterMiner
    id: SalvagerPDA
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHatBeretFederation

- type: startingGear
  id: SV_CybersunRep
  equipment:
    jumpsuit: ClothingUniformJumpsuitCybersunRep
    shoes: ClothingShoesBootsLaceup
    id: PassengerPDA
