// SPDX-FileCopyrightText: 2025 Wizards Den contributors
// SPDX-FileCopyrightText: 2025 Sector Vestige contributors (modifications)
// SPDX-FileCopyrightText: 2022 Rane <60792108+Elijahrane@users.noreply.github.com>
// SPDX-FileCopyrightText: 2023 PrPleGoo <PrPleGoo@users.noreply.github.com>
// SPDX-FileCopyrightText: 2023 Vordenburg <114301317+Vordenburg@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 AJCM-git <60196617+AJCM-git@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 BuildTools <unconfigured@null.spigotmc.org>
// SPDX-FileCopyrightText: 2024 Nemanja <98561806+EmoGarbage404@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Ty Ashley <42426760+TyAshley@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 slarticodefast <161409025+slarticodefast@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Brandon Li <48413902+aspiringLich@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Connor Huffine <chuffine@gmail.com>
// SPDX-FileCopyrightText: 2025 LordCarve <27449516+LordCarve@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 ReboundQ3 <22770594+ReboundQ3@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 ReboundQ3 <ReboundQ3@gmail.com>
// SPDX-FileCopyrightText: 2025 qu4drivium <aaronholiver@outlook.com>
//
// SPDX-License-Identifier: MIT

using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Access.Components;
using Content.Shared.CCVar;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using System.Numerics;
using System.Linq;
using Content.Shared._CD.NanoChat;

namespace Content.Client.Access.UI;

[GenerateTypedNameReferences]
public sealed partial class AgentIDCardWindow : FancyWindow
{
    [Dependency] private IConfigurationManager _cfgManager = default!;
    [Dependency] private IEntitySystemManager _entitySystem = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    private readonly SpriteSystem _spriteSystem;

        private const int MaxNumberLength = 4; // CD - Same as NewChatPopup

        public event Action<string>? OnNameChanged;
        public event Action<string>? OnJobChanged;

        public event Action<uint>? OnNumberChanged; // CD - Add event for number changes

        public event Action<ProtoId<JobIconPrototype>>? OnJobIconChanged;

    public AgentIDCardWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _spriteSystem = _entitySystem.GetEntitySystem<SpriteSystem>();

        NameLineEdit.OnTextEntered += e => CommitName(e.Text);
        NameLineEdit.OnFocusExit += e => CommitName(e.Text);

        JobLineEdit.OnTextEntered += e => CommitJob(e.Text);
        JobLineEdit.OnFocusExit += e => CommitJob(e.Text);

        NameLineEdit.IsValid = s => s.Length <= _cfgManager.GetCVar(CCVars.MaxNameLength);
        JobLineEdit.IsValid = s => s.Length <= _cfgManager.GetCVar(CCVars.MaxIdJobLength);

        AgentTabs.SetTabTitle(0, Loc.GetString("agent-id-ui-tab-settings"));
        AgentTabs.SetTabTitle(1, Loc.GetString("agent-id-ui-tab-job-icons"));

        // CD - Add handlers for number changes
        NumberLineEdit.OnTextEntered += OnNumberEntered;
        NumberLineEdit.OnFocusExit += OnNumberEntered;

        // CD - Filter to only allow digits
        NumberLineEdit.OnTextChanged += args =>
        {
            if (args.Text.Length > MaxNumberLength)
            {
                NumberLineEdit.Text = args.Text[..MaxNumberLength];
            }

            // Filter to digits only
            var newText = string.Concat(args.Text.Where(char.IsDigit));
            if (newText != args.Text)
                NumberLineEdit.Text = newText;
        };
    }

    // CD - Add number validation and event
    private void OnNumberEntered(LineEdit.LineEditEventArgs args)
    {
        if (uint.TryParse(args.Text, out var number) && number > 0)
            OnNumberChanged?.Invoke(number);
        NumberLineEdit.Text = number.ToString("D4") ?? "";
    }

    // CD - Add setter for current number
    public void SetCurrentNumber(uint? number)
    {

    }

    /// <summary>
    /// Creates the job icons tab.
    /// </summary>
    public void SetAllowedIcons(IReadOnlyList<ProtoId<JobIconGroupPrototype>> jobGroups, ProtoId<JobIconPrototype> currentIcon)
    {
        JobGroupGrid.DisposeAllChildren();
        IconGrid.DisposeAllChildren();

        var jobGroupButtonGroup = new ButtonGroup();
        ContainerButton? firstGroupButton = null;
        IReadOnlyList<ProtoId<JobIconPrototype>>? firstGroupIcons = null;
        ContainerButton? matchingGroupButton = null;
        IReadOnlyList<ProtoId<JobIconPrototype>>? matchingGroupIcons = null;

        foreach (var group in jobGroups)
        {
            if (!_prototypeManager.TryIndex(group, out var groupProto))
                continue;

            var groupButton = CreateGroupButton(groupProto, jobGroupButtonGroup);
            groupButton.OnPressed += _ => SetJobIcons(groupProto.Icons);

            JobGroupGrid.AddChild(groupButton);

            firstGroupButton ??= groupButton;
            firstGroupIcons ??= groupProto.Icons;

            // Prefer the group that actually contains the card's current icon so
            // the opened window shows the relevant set rather than always the first.
            if (matchingGroupButton == null && groupProto.Icons.Contains(currentIcon))
            {
                matchingGroupButton = groupButton;
                matchingGroupIcons = groupProto.Icons;
            }
        }

        var selectedButton = matchingGroupButton ?? firstGroupButton;
        var selectedIcons = matchingGroupIcons ?? firstGroupIcons;

        if (selectedButton == null || selectedIcons == null)
            return;

        selectedButton.Pressed = true;
        SetJobIcons(selectedIcons);
    }

    /// <summary>
    /// Creates the job icon subgroup within the job icons tab.
    /// </summary>
    private void SetJobIcons(IReadOnlyList<ProtoId<JobIconPrototype>> jobIcons)
    {
        IconGrid.DisposeAllChildren();

        foreach (var icon in jobIcons)
        {
            if (!_prototypeManager.TryIndex(icon, out var iconProto))
                continue;

            var texture = _spriteSystem.Frame0(iconProto.Icon);

            // Create new button
            var jobIconButton = new TextureButton
            {
                Access = AccessLevel.Public,
                ToolTip = Loc.GetString(iconProto.JobName),
                TextureNormal = texture,
                SetSize = new Vector2(32, 32),
            };

            // Finish button and add to UI
            jobIconButton.OnPressed += _ => OnJobIconChanged?.Invoke(iconProto.ID);

            IconGrid.AddChild(jobIconButton);
        }
    }

    public void Update(IdCardComponent card, NanoChatCardComponent nanoChat)
    {
        var name = card.FullName ?? string.Empty;
        var job = card.LocalizedJobTitle ?? string.Empty;
        var number = nanoChat.Number?.ToString() ?? string.Empty;

        NameLineEdit.Text = name;
        CurrentName.Text = name;
        JobLineEdit.Text = job;
        CurrentJob.Text = job;
        NumberLineEdit.Text = number;
        CurrentNumber.Text = number;

        var jobIconProto = _prototypeManager.Index(card.JobIcon);
        CurrentJobIcon.Texture = _spriteSystem.Frame0(jobIconProto.Icon);
    }

    private ContainerButton CreateGroupButton(JobIconGroupPrototype groupProto, ButtonGroup buttonGroup)
    {
        var button = new ContainerButton
        {
            Access = AccessLevel.Public,
            Group = buttonGroup,
            ToggleMode = true,
            StyleClasses = { StyleClass.ButtonOpenBoth },
            Margin = new Thickness(8, 2)
        };

        button.AddChild(new BoxContainer
        {
            SeparationOverride = 8,
            Children =
            {
                new TextureRect
                {
                    Texture = _spriteSystem.Frame0(groupProto.Sprite),
                    Stretch = TextureRect.StretchMode.KeepAspectCentered,
                    SetSize = new Vector2(32, 32),
                    VerticalAlignment = VAlignment.Center,
                },
                new Label
                {
                    Text = Loc.GetString(groupProto.GroupName),
                    HorizontalExpand = true,
                    VerticalAlignment = VAlignment.Center,
                },
            },
        });

        return button;
    }

    private void CommitJob(string job)
    {
        OnJobChanged?.Invoke(job);
    }

    private void CommitName(string name)
    {
        OnNameChanged?.Invoke(name);
    }
}
